### ISSUE TITLE
Session Corrupt - methodCallExpression is null

### ISSUE THREAD

**Issue by TheAmg** [unloggedio/intellij-java-plugin#25]
### Describe the bug

The following exception trace was sent by a user ->

Exception trace - 
```
2024-07-30 17:25:41,957 [3243372]   WARN - #com.insidious.plugin.client.SessionInstance - processing [3263] events from [2] log files: 2432009
2024-07-30 17:25:41,959 [3243374]   WARN - #com.insidious.plugin.client.SessionEventReader - Finished reading events [2] log files in [43 ms ]
2024-07-30 17:25:42,023 [3243438]   INFO - STDERR - java.lang.NullPointerException: Cannot invoke "com.insidious.plugin.pojo.dao.MethodCallExpression.getCallTimeNano()" because "methodCallExpression" is null
2024-07-30 17:25:42,035 [3243450]   INFO - STDERR - 	at com.insidious.plugin.client.SessionInstance.processLogFile(SessionInstance.java:3526)
2024-07-30 17:25:42,035 [3243450]   INFO - STDERR - 	at com.insidious.plugin.client.SessionInstance.processPendingThreadFiles(SessionInstance.java:2467)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at com.insidious.plugin.client.SessionInstance.scanDataAndBuildReplay(SessionInstance.java:2379)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at com.insidious.plugin.client.SessionInstance.run(SessionInstance.java:4161)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-07-30 17:25:42,036 [3243451]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2024-07-30 17:25:42,039 [3243454]   WARN - #com.insidious.plugin.client.SessionInstance - Exception in scan and build session
java.lang.NullPointerException: Cannot invoke "com.insidious.plugin.pojo.dao.MethodCallExpression.getCallTimeNano()" because "methodCallExpression" is null
	at com.insidious.plugin.client.SessionInstance.processLogFile(SessionInstance.java:3526)
	at com.insidious.plugin.client.SessionInstance.processPendingThreadFiles(SessionInstance.java:2467)
	at com.insidious.plugin.client.SessionInstance.scanDataAndBuildReplay(SessionInstance.java:2379)
	at com.insidious.plugin.client.SessionInstance.run(SessionInstance.java:4161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2024-07-30 17:25:42,198 [3243613]   WARN - #com.insidious.plugin.factory.UsageInsightTracker - RecordEvent [SESSION_CORRUPT]
2024-07-30 17:25:42,411 [3243826]   INFO - #com.insidious.plugin.client.ZipConsumer - open archive [/home/./.unlogged/sessions/selogger-output-20240730-074646486/index-00079-1722340480938.zip] last modified=[1722340542393], lastChecked = [1722340540603]
```

### Reproduction steps

To be Identified.
...

### Expected behavior

For Scan to not break.

### Additional context

Logs : https://drive.google.com/file/d/1lR9wn--gJRG13Zoc4T9T9HpLXGIGxWzT/view?usp=sharing

**Comment by artpar** [comment]
does rescanning this also result into session corrupt ?
